// Centralized Translations for ISOKI Match Portal (Indonesian & English Bilingual support)

export type LangType = 'ID' | 'EN';

export const TRANSLATIONS = {
  ID: {
    // Nav & Menu
    home: 'Beranda',
    matchday: 'Matchday',
    members: 'Member',
    finance: 'Keuangan',
    loggedAs: 'Masuk Sebagai',
    logout: 'Keluar',

    // Generic states & actions
    add: 'Tambah',
    edit: 'Ubah',
    delete: 'Hapus',
    save: 'Simpan',
    cancel: 'Batal',
    back: 'Kembali',
    action: 'Aksi',
    all: 'Semua',
    close: 'Tutup',
    active: 'Aktif',
    inactive: 'Nonaktif',
    status: 'Status',
    total: 'Total',
    date: 'Tanggal',

    // Dashboard Hub
    totalRoster: 'Total Roster',
    activeRoster: 'Roster Aktif',
    netBalance: 'Saldo Kas',
    income: 'Uang Masuk',
    expense: 'Uang Keluar',
    recentTransactions: 'Transaksi Terakhir',
    newRoster: 'Roster Terbaru',
    seeAll: 'Lihat Semua',
    noTransactions: 'Belum ada pencatatan kas/iuran.',
    noRoster: 'Belum ada roster terdaftar.',
    realtimeUpdateTip: 'Kas realtime diperbarui otomatis pada setiap pencatatan iuran baru.',
    rosterTip: 'Daftarkan nomor WhatsApp member untuk mempermudah koordinasi pertandingan.',
    quickAddMem: '📞 Roster Baru',
    quickAddTx: '💸 Catat Iuran',

    // Auth screen
    portalTitle: 'Portal Manajemen Tim',
    loginTab: '🔑 Masuk Portal',
    registerTab: '🛡️ Buat Tim Baru',
    adminLoginHeader: 'Masuk Portal Admin',
    loginSubtitle: 'Masukkan credentials admin klub Anda untuk masuk.',
    usernameLabel: 'Nama Pengguna Admin',
    passwordLabel: 'Sandi Keamanan',
    loginBtn: 'Masuk Sekarang',
    instantDemoBtn: '🚀 Masuk Instan (Demo Garuda MFC)',
    registerOnboardHeader: 'Setup Onboarding Klub Olahraga',
    registerDescr: 'Dirancang fleksibel untuk segala jenis komunitas cabang olahraga. Singkatan nama tim Anda akan digunakan secara otomatis untuk penomoran kode anggota baru.',
    clubNameLabel: 'Nama Tim Olahraga',
    clubAbbrevLabel: 'Singkatan Kode',
    sportBranchLabel: 'Cabang Olahraga Tim',
    themeColorLabel: 'Pilihan Warna Tema Tim',
    crestLabel: 'Lambang Kebesaran Tim',
    uploadCrestBtn: 'Pilih File Logo',
    activeCrestAlert: 'Lambang Berhasil Diunggah!',
    noUploadInfo: 'Inisial Shield Crest Vector otomatis dirancang berorientasi warna tema pilihan Anda.',
    dragDropText: 'Tarik file logo tim Anda di sini, atau',
    dragDropSub: 'PNG, JPG, ATAU WEBP (MAKS 2MB)',
    registerSubmitBtn: '🏁 Buat Club & Mulai Bersih',

    // Matchdays Panel
    scheduleTitle: 'Kalender Match Schedule',
    addMatchBtn: '📅 Jadwal Sesi Baru',
    searchMatchPlaceholder: 'Cari sesi matchday...',
    opponent: 'Lawan / Internal Match',
    location: 'Lokasi / Lapangan',
    time: 'Jam Kick-off',
    rentCost: 'Biaya Sewa Lapangan',
    totalRentPaid: 'Biaya Sewa Terbayar',
    matchStatusPlanned: 'Direncanakan',
    matchStatusDone: 'Selesai',
    matchStatusCanceled: 'Dibatalkan',
    attendance: 'Kehadiran Roster',
    matchSummary: 'Rangkuman Sesi Match',
    attendanceRate: 'Tingkat Kehadiran',
    attended: 'Hadir',
    absent: 'Tidak Hadir',
    unconfirmed: 'Belum Konfirmasi',
    matchFinance: 'Arus Kas Match',
    feePerPlayer: 'Iuran Wajib Perorang',
    totalCollected: 'Total Uang Terkumpul',
    unpaidPlayers: 'Pemain Belum Bayar',
    sessionLogs: 'Histori Pertandingan',
    prevMatches: 'Pertandingan Sebelumnya',
    emptyHomeMatches: 'Belum menetapkan jadwal matchday. Klik tombol di atas untuk membuat jadwal sesi pertandingan pertama tim Anda!',
    emptyMatches: 'Belum ada agenda jadwal pertandingan.',

    // Member List
    memberListTitle: 'Database Roster Tim',
    searchMemberPlaceholder: 'Cari nama atau kode member...',
    addMemberBtn: '👤 Tambah Roster Baru',
    memberCode: 'Kode Anggota',
    memberName: 'Nama Lengkap Roster',
    rolePosition: 'Posisi Bermain',
    waNumber: 'Nomor WhatsApp',
    waPlaceholder: 'Contoh: 081234567890',
    joinedDate: 'Tanggal Bergabung',
    statusAktif: 'Status Keanggotaan',
    optionalProfilePic: 'Foto Profil Roster',
    gantiFoto: 'Ganti Foto Roster',
    pilihFoto: 'Pilih Foto Roster',
    hapusFoto: 'Hapus',
    fotoTip: 'Unggah foto berkualitas persegi (.png atau .jpg) maksimal 2MB.',

    // Financial Ledger
    ledgerTitle: 'Jurnal Arus Kas Keuangan',
    addTransactionBtn: '💰 Catat Arus Kas Baru',
    searchTxPlaceholder: 'Cari transaksi / deskripsi...',
    allKategori: 'Semua Kategori',
    kategoriSewa: 'Sewa Lapangan',
    kategoriIuran: 'Iuran Member',
    kategoriSponsorship: 'Sponsor / Donasi',
    kategoriLainnya: 'Penyesuaian / Lainnya',
    txDescription: 'Keterangan Transaksi',
    txAmount: 'Jumlah Nominal (Rupiah)',
    txType: 'Jenis Transaksi',
    txCategory: 'Kategori Kas',
    assocMember: 'Hubungkan dengan Member (Opsional)',
    noAssoc: 'Umum / Tanpa Member',
    descPlaceholder: 'Contoh: Sewa lapangan pekan 4',
    amountPlaceholder: 'Contoh: 150000',
    txRealtimeLog: 'Buku Jurnal Keuangan Utama',
    recentLogs: 'Semua Transaksi',
  },
  EN: {
    // Nav & Menu
    home: 'Home',
    matchday: 'Matchdays',
    members: 'Roster',
    finance: 'Finance',
    loggedAs: 'Logged in as',
    logout: 'Logout',

    // Generic states & actions
    add: 'Add',
    edit: 'Edit',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    back: 'Back',
    action: 'Action',
    all: 'All',
    close: 'Close',
    active: 'Active',
    inactive: 'Inactive',
    status: 'Status',
    total: 'Total',
    date: 'Date',

    // Dashboard Hub
    totalRoster: 'Total Roster',
    activeRoster: 'Active Roster',
    netBalance: 'Club Balance',
    income: 'Total Income',
    expense: 'Total Expenses',
    recentTransactions: 'Recent Transactions',
    newRoster: 'New Roster',
    seeAll: 'See All',
    noTransactions: 'No transaction entries logged yet.',
    noRoster: 'No squad members registered.',
    realtimeUpdateTip: 'Real-time club balance automatically updates on every ledger change.',
    rosterTip: 'Include WhatsApp contacts to streamline matchday communication.',
    quickAddMem: '📞 New Roster',
    quickAddTx: '💸 Log Fee',

    // Auth screen
    portalTitle: 'Team Management Portal',
    loginTab: '🔑 Login Portal',
    registerTab: '🛡️ Register Club',
    adminLoginHeader: 'Admin Login',
    loginSubtitle: 'Enter your admin security credentials to access the workspace.',
    usernameLabel: 'Admin Username',
    passwordLabel: 'Security Password',
    loginBtn: 'Log In Now',
    instantDemoBtn: '🚀 Fast Login (Demo Club)',
    registerOnboardHeader: 'Sport Club Registration',
    registerDescr: 'Built flexibly for all kinds of sport and community groups. Your abbreviation automatically structures newly generated registry codes.',
    clubNameLabel: 'Sport Team Name',
    clubAbbrevLabel: 'Initials / Abbr.',
    sportBranchLabel: 'Sporting Branch',
    themeColorLabel: 'Team Palette Theme',
    crestLabel: 'Team Shield / Logo Badge',
    uploadCrestBtn: 'Upload Badge',
    activeCrestAlert: 'Logo Uploaded Successfully!',
    noUploadInfo: 'Initial Vector Shield custom designed based on your chosen palette theme.',
    dragDropText: 'Drag your logo file here, or',
    dragDropSub: 'PNG, JPG, OR WEBP (MAX 2MB)',
    registerSubmitBtn: '🏁 Create Club & Setup Database',

    // Matchdays Panel
    scheduleTitle: 'Match Schedules',
    addMatchBtn: '📅 New Matchday Sesi',
    searchMatchPlaceholder: 'Search sessions...',
    opponent: 'Opponent / Sub-Match',
    location: 'Pitch / Venue',
    time: 'Kick-off Time',
    rentCost: 'Rent Expense',
    totalRentPaid: 'Rent Rental Paid',
    matchStatusPlanned: 'Scheduled',
    matchStatusDone: 'Played',
    matchStatusCanceled: 'Postponed',
    attendance: 'Squad Lineup Status',
    matchSummary: 'Match Overview',
    attendanceRate: 'Attendance Rate',
    attended: 'Present',
    absent: 'Absent',
    unconfirmed: 'Unconfirmed',
    matchFinance: 'Match Ledger',
    feePerPlayer: 'Target Contribution',
    totalCollected: 'Total Collected',
    unpaidPlayers: 'Outstanding Fees',
    sessionLogs: 'Match History',
    prevMatches: 'Historical Fixtures',
    emptyHomeMatches: 'No fixtures schedule declared. Click new session button to seed your roster schedule!',
    emptyMatches: 'No agendas found in scheduler database.',

    // Member List
    memberListTitle: 'Active Squad Roster',
    searchMemberPlaceholder: 'Search by name or code...',
    addMemberBtn: '👤 Add Squad Player',
    memberCode: 'Registry Code',
    memberName: 'Player Name',
    rolePosition: 'Lineup Role / Position',
    waNumber: 'WhatsApp No.',
    waPlaceholder: 'e.g. 628123456789',
    joinedDate: 'Affiliation Date',
    statusAktif: 'Squad Status',
    optionalProfilePic: 'Player Snapshot',
    gantiFoto: 'Change Avatar',
    pilihFoto: 'Browse Photo',
    hapusFoto: 'Remove',
    fotoTip: 'Upload a square aspect ratio profile picture, max 2MB.',

    // Financial Ledger
    ledgerTitle: 'Financial Cash Register',
    addTransactionBtn: '💰 Post New Transaction',
    searchTxPlaceholder: 'Search cash columns...',
    allKategori: 'All Categories',
    kategoriSewa: 'Field Rental',
    kategoriIuran: 'Player Contributions',
    kategoriSponsorship: 'Patronage & Sponsor',
    kategoriLainnya: 'Misc. Balancing',
    txDescription: 'Posting Narrative',
    txAmount: 'Amount Spent/Received (Rp)',
    txType: 'Posting Type',
    txCategory: 'Posting Ledger Category',
    assocMember: 'Associate with Player (Optional)',
    noAssoc: 'General Posting (No Player)',
    descPlaceholder: 'e.g. Booking Pitch Session 4',
    amountPlaceholder: 'e.g. 150000',
    txRealtimeLog: 'Primary Book Ledger',
    recentLogs: 'All Historical Entries',
  }
};
